ARG RUBY_VERSION=3.2.2
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    pkg-config \
    curl \
    libvips \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails
ENV RAILS_ENV="development" \
    BUNDLE_PATH="/usr/local/bundle"

EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
